"""
Builds the retrieval-vs-generation comparison CSV from output/rag_eval.json.

Generated answers come from rag_eval.json; the verdicts/winner/why columns
are a manual analysis of retrieval relevance and answer quality for each
(question, method) pair.

Run from the repo root:
    uv run python 4_retrieval/build_comparison_csv.py

Writes output/retrieval_comparison.csv
"""

import csv
import json
from pathlib import Path

RAG_EVAL_PATH = Path(__file__).parent.parent / "output" / "rag_eval.json"
OUTPUT_PATH = Path(__file__).parent.parent / "output" / "retrieval_comparison.csv"

ANALYSIS = {
    "How does an AI agent decide what actions to take?": {
        "semantic": "Retrieval: Good (3/5 relevant - \"A Primer on How AI Agents Work\" plus two \"Understanding the 6 Levels of Agent Autonomy\" chunks; 2 slots are generic/title-only). Generation: Good - covers the model-as-brain reasoning framing and how the agent's autonomy level (explicit goals vs. self-determined goals) shapes its decisions, but stays fairly general.",
        "bm25": "Retrieval: Partial (2/5 clearly relevant - the \"A 6-Step Framework for Designing Agentic Applications\" step3/step4 chunk and \"Today's Agenda\"; the rest are tangential RAG-pipeline/embedding-model chunks). Generation: Very good - despite thin retrieval, grounds the answer in concrete decision steps (select/reject/escalate to a human), action inference via APIs (email, CRM), and the system-prompt framing.",
        "hybrid": "Retrieval: Good (mix of RAG-pipeline, \"Context Engineering\", the \"6-Step Framework\" step3/step4 chunk, and \"A Primer on How AI Agents Work\"). Generation: Best - combines decision-making based on user intent/goals, action evaluation via APIs, and risk-factor assessment at each step - the most complete answer of the three.",
        "rewritten_reranked": "Retrieval: Good (3/5 relevant - \"A Primer on How AI Agents Work\", the \"Agentic RAG Demo: Complex Queries and Tool Selection\" chunk on intent-based tool selection, and the \"6-Step Framework\" chunk; 2 slots are tangential code-walkthrough continuations). Generation: Good - covers user-intent reasoning, task decomposition, and intent-based tool/dataset selection. RAGAS: 1.0 / 0.86 / 1.0 - the only metric where it trails the leaders is answer_relevancy.",
        "winner": "Hybrid",
        "why": "RAGAS confirms hybrid and bm25 both score a perfect 1.0/1.0/1.0 on this question - hybrid's richer chunk mix (6-Step Framework + Primer + RAG-pipeline context) and bm25's own 6-step-framework chunk both ground complete answers covering decision criteria, action inference, and risk factors. rewritten_reranked is close (1.0/0.86/1.0) with similar retrieval but a slightly less on-target answer; semantic trails on context_recall (0.8).",
    },
    "How does a transformer understand relationships between words?": {
        "semantic": "Retrieval: Excellent (4/5 relevant - three \"The Illustrated Transformer\" chunks, \"Attention Is All You Need\", plus a transformer-architecture transcript chunk). Generation: Good - covers self-attention and positional encoding clearly, though doesn't surface the Query/Key/Value vector mechanism.",
        "bm25": "Retrieval: Good (3/5 relevant - two \"Illustrated Transformer\" chunks plus \"Attention Is All You Need\"; the other 2 are a tangential \"Evolution of LLMs\" chunk and an Illustrated-Transformer discussion-links chunk). Generation: Good - same self-attention + positional-encoding coverage as semantic, comparable quality.",
        "hybrid": "Retrieval: Excellent (4/5 relevant - three \"Illustrated Transformer\" chunks plus \"Attention Is All You Need\"). Generation: Good - self-attention + positional encoding, on par with semantic and BM25.",
        "rewritten_reranked": "Retrieval: Excellent (5/5 relevant - three \"Illustrated Transformer\" chunks plus \"Attention Is All You Need\", same strong set as semantic/hybrid). Generation: Best - the only method to also surface the Query/Key/Value weight-matrix detail of multi-headed attention, in addition to self-attention and positional encoding, closing the QKV gap noted for the other three methods. RAGAS: 0.91 / 1.0 / 1.0 - a small faithfulness trade-off but perfect relevancy/recall.",
        "winner": "Rewritten+Reranked",
        "why": "rewritten_reranked is the only method whose answer covers all three mechanisms - self-attention, positional encoding, AND the Query/Key/Value weight matrices behind multi-headed attention - resolving the QKV gap noted in every prior run. RAGAS shows a small faithfulness trade-off (0.91 vs 1.0 for the others), but answer_relevancy and context_recall remain perfect, and the added mechanistic detail makes this the most complete answer of the four.",
    },
    "How do prompts influence model behavior?": {
        "semantic": "Retrieval: Excellent (5/5 relevant - \"Essential LLM Terminology Explained\", \"Prompt Anti-Patterns\", \"Prompt Engineering Fundamentals\" (Claude docs), \"Prompting Fundamentals and Advanced Techniques\", and \"Prompt Engineering vs. Context Engineering\"). Generation: Best - covers the prompt definition, anti-patterns/clarity effects, the system-prompt vs. user-prompt distinction, AND assistant pre-filling as a steering technique.",
        "bm25": "Retrieval: Partial (2/5 relevant - \"Prompt Anti-Patterns\" and \"Prompting Fundamentals\"; the other 3 are LangChain/N8N-framework and project-closing chunks). Generation: Decent - covers steering/clarity and prompt-management tooling, but misses the system-prompt distinction and pre-filling technique.",
        "hybrid": "Retrieval: Good (3/5 relevant - \"Prompt Anti-Patterns\", \"Essential LLM Terminology\", and \"Prompt Engineering Fundamentals\" (Claude docs); 2 LangChain/N8N-framework chunks add little). Generation: Good - covers the prompt definition, anti-patterns, and the importance of prompt engineering for steering output, but thinner than semantic (no system-prompt distinction or pre-filling).",
        "rewritten_reranked": "Retrieval: Weak (0/5 relevant - the rewritten query drifted toward agent/course-structure terminology (\"Table of Content\", \"Introduction to AI Agents and Harnesses\", \"Week 1 Recap and the Need for RAG\", \"A Primer on How AI Agents Work\"), missing the prompt-engineering chunks (\"Prompt Anti-Patterns\", \"Prompt Engineering Fundamentals\") that semantic/hybrid retrieve). Generation: Weak - falls back to a generic answer about separating prompts from code and structuring prompts for user intent, without anti-patterns, the system/user-prompt distinction, or pre-filling. RAGAS answer_relevancy is the lowest of the four methods (0.79).",
        "winner": "Semantic",
        "why": "With OpenAI embeddings, semantic retrieval is now 5/5 relevant - including a new web source (\"Prompt Engineering Fundamentals\", Claude docs) not surfaced before - giving the LLM the richest context (anti-patterns + system/user prompt distinction + assistant pre-filling) and the most complete answer. This flips the previous winner (Hybrid), whose retrieval mix is now diluted by 2 LangChain/N8N chunks that crowd out some of semantic's strongest hits. This is also the one question where query rewriting hurts: the rewritten query drifts toward \"agent\"/course-structure framing instead of \"prompt engineering\", so rewritten_reranked's candidate pool misses the prompt-specific chunks entirely and produces the most generic of the four answers (RAGAS answer_relevancy 0.79, lowest of the four).",
    },
    "What are good ways to judge whether an LLM output is correct?": {
        "semantic": "Retrieval: Weak (1/5 relevant - only \"RAG Evaluation Metrics\"; the other 4 are about structured output/function calling and prompting, not evaluation). Generation: Poor - hedges into \"I cannot provide a definitive answer\", mentioning only the \"LLM as a judge\" concept.",
        "bm25": "Retrieval: Partial (2/5 relevant - \"RAG Evaluation Metrics\" and one \"Conclusion and Q&A: LLM as a judge\" chunk; the rest are repeated/tangential Q&A chunks). Generation: Poor - same hedge pattern as semantic.",
        "hybrid": "Retrieval: Partial (2/5 relevant - \"RAG Evaluation Metrics\" and \"Conclusion and Q&A\"; the rest overlap with semantic's structured-output chunks). Generation: Poor - still hedges into a non-answer.",
        "rewritten_reranked": "Retrieval: Good (1/5 directly relevant, but it's the right one - \"§12 RAG EVALS: Frameworks that do the boilerplate for you (RAGAS, TruLens)\" from Week 2-Session 2.pdf, the evaluation-frameworks chunk none of the other methods surface; the other 4 slots are tangential structured-output/function-calling/LLM-evolution chunks). Generation: Best - confidently names RAGAS (faithfulness, answer relevance), the \"Feedback functions\" framework, DeepEval/Promptfoo/LangSmith/Langfuse, and LLM-as-judge - no hedging. RAGAS: 1.0 / 0.99 / 1.0.",
        "winner": "Rewritten+Reranked",
        "why": "All three original methods hedge into \"I cannot provide a definitive answer\" (RAGAS confirms semantic/hybrid both score 0.75/0.0/0.0 - a noncommittal response). Query rewriting reformulates this conversational question into evaluation-framework terminology, surfacing the §12 RAG EVALS chunk (RAGAS/TruLens/faithfulness/answer-relevance) that semantic and hybrid never retrieve in their top 5. rewritten_reranked instead gives a confident, grounded, multi-framework answer (RAGAS: 1.0/0.99/1.0). bm25 also does reasonably well here (1.0/0.86/1.0) via its own retrieval of related Q&A chunks, but rewritten_reranked is the clear winner - this is the headline result of the RAGAS evaluation.",
    },
    "What components do agentic AI systems need?": {
        "semantic": "Retrieval: Excellent (5/5 relevant - three \"Exploring Agentic Frameworks: The AI Tech Stack\" chunks, the \"A 6-Step Framework for Designing Agentic Applications\" chapter chunk, and \"Deep Dive: The AI Agent Tech Stack\"). Generation: Excellent - confidently lists 4 concrete components (Domain Knowledge, Goals, Inputs, Tools) drawn from the 6-step-framework chapter, with no hedging.",
        "bm25": "Retrieval: Partial (1/5 relevant - \"Exploring Agentic Frameworks: The AI Tech Stack\"; the rest are LangChain/N8N comparison, course agenda, and Q&A chunks that miss the 6-step-framework chapter). Generation: Poor - hedges into \"cannot provide a definitive answer\".",
        "hybrid": "Retrieval: Good (3/5 relevant - two \"Exploring Agentic Frameworks: The AI Tech Stack\" chunks plus the \"A 6-Step Framework\" chapter chunk). Generation: Excellent - same confident 4-component answer (Domain Knowledge, Goals, Inputs, Tools) as semantic, nearly identical quality.",
        "rewritten_reranked": "Retrieval: Partial (2/5 relevant - a \"we will take a closer look at all of these components\" lead-in and a \"why agentic frameworks\" discussion, both from session2-week1; the other 3 are LangChain/N8N-comparison, RAG-lightning-lesson, and course-agenda chunks). Generation: Excellent - lists 7 components (Prompt Management, Tool Management, RAG, Basic Agents, Memory, Complex Workflows, Multi-Agent Systems) from the \"AI Tech Stack\" framing - a different but equally valid enumeration from semantic/hybrid's 4-component (Domain Knowledge, Goals, Inputs, Tools) \"6-Step Framework\" answer. RAGAS: 1.0 / 0.94 / 1.0, essentially tied with semantic/hybrid (1.0/0.945/1.0).",
        "winner": "Semantic / Hybrid / Rewritten+Reranked (tie)",
        "why": "This flips dramatically from the prior run, where all three original methods hedged. With OpenAI embeddings, both semantic and hybrid retrieve the \"A 6-Step Framework for Designing Agentic Applications\" chapter-overview chunk, which explicitly enumerates the prerequisites (domain knowledge, goals, inputs, tools) for building an agentic application - letting both produce a confident, well-structured, near-identical answer. rewritten_reranked lands a near-identical RAGAS score (1.0/0.94/1.0) via a different but equally valid \"AI Tech Stack\" component framing (Prompt/Tool Management, RAG, Memory, Multi-Agent Systems, etc.) - both are correct answers grounded in different parts of the corpus. BM25 still misses both chunk sets and hedges; its answer_relevancy=0.0 is consistent with RAGAS's noncommittal-response scoring (same pattern as Q4), not a separate anomaly.",
    },
    "What is BM25?": {
        "semantic": "Retrieval: Excellent (4/5 relevant - Week 2-Session 1.pdf p.25 \"BM25 is the king of this family\", p.39 (TF/IDF/length-normalization scoring detail), p.40 \"BM25 beats vectors\", and a transcript chunk on BM25 vs. vector search). Generation: Excellent - comprehensive, cites all three PDF pages plus the transcript, covering definition, scoring factors, and use cases.",
        "bm25": "Retrieval: Failed (0/5 relevant - same as before: \"Introduction to RAG Evaluation\", \"A Primer on How AI Agents Work\", \"Project 2 Overview\", \"Building a Golden Dataset\", \"Demo Part 1\" - none mention BM25's definition). Generation: Honest failure - \"the provided context does not contain any information about BM25\".",
        "hybrid": "Retrieval: Good (2/5 relevant - recovers p.25 and p.39 via the semantic leg; the other 3 BM25-only slots are the same irrelevant chunks as BM25-only). Generation: Excellent - nearly matches semantic, citing p.25 and p.39 with TF/IDF/length-normalization detail.",
        "rewritten_reranked": "Retrieval: Excellent (5/5 relevant - all three BM25-definition chunks from Week 2-Session 1.pdf (p.25 \"king of this family\", p.39 inverted-index/TF-IDF/length-normalization scoring, p.40 \"BM25 beats vectors\"), plus the \"Hybrid Search and Re-ranking Techniques\" transcript chunk and the \"don't pick - just use both\" dense+sparse recipe chunk). Generation: Excellent - matches semantic's coverage of definition, scoring factors, and use cases, citing p.25/p.39/p.40.",
        "winner": "Semantic / Rewritten+Reranked (tie)",
        "why": "Confirms the documented IDF limitation persists independent of the embedding-model swap: BM25's own retrieval still completely misses the chunks that define BM25 (the term \"bm25\" is too frequent across the corpus - low IDF - to be discriminative), so BM25-only retrieval and generation both fail outright. Semantic search (OpenAI embeddings) retrieves all the right slides and produces a fully cited, comprehensive answer; rewritten_reranked now matches (and arguably slightly exceeds) it - 5/5 relevant chunks including the dense+sparse \"use both\" recipe that semantic doesn't surface. Hybrid recovers most of it through its semantic leg.",
    },
    "What does the course say about Pinecone?": {
        "semantic": "Retrieval: Excellent (5/5 relevant - \"The Vector Search Pipeline\" (guest-lecture mention), two \"Demo Part 1/2\" chunks on Pinecone usage, and Week 2-Session 1.pdf p.13 on vector-search/ANN/Pinecone features). Generation: Excellent - comprehensive, covers Pinecone as a managed vector DB, ANN index, metadata filters, hybrid search, and the guest lecture.",
        "bm25": "Retrieval: Failed (0/5 relevant - \"Today's Agenda\", \"Live Demo: create_agent\", \"Context Engineering with Many Tools\", \"Live Demo: Stock Portfolio Analyzer\", and \"Agent Harness\" - none mention Pinecone). Generation: Honest failure - \"the provided context does not contain any information about Pinecone\".",
        "hybrid": "Retrieval: Partial (2/5 relevant - \"The Vector Search Pipeline\" and \"Demo Part 1\" recovered via the semantic leg; the other 3 BM25-only slots are irrelevant). Generation: Good - covers Pinecone as a vector DB for semantic search/RAG at scale and the guest lecture, but misses the ANN-index/metadata-filter detail semantic includes.",
        "rewritten_reranked": "Retrieval: Good (4/5 relevant - the \"how vector search actually runs\" / ANN slide, the guest-lecture mention, the SQL-vs-vector-DB framing, and the direct \"every chunk has an embedding... stored like this in Pinecone\" explanation; 1 slot on \"narrowing down your scope\" is tangential). Generation: Excellent - covers Pinecone as a managed vector DB (ANN index, metadata filters, hybrid search, durability/replication/autoscaling), the guest lecture, and the \"don't build your own vector search pipeline\" framing - matches semantic's comprehensiveness.",
        "winner": "Semantic / Rewritten+Reranked (tie)",
        "why": "Same pattern as before the embedding swap: BM25's whitespace tokenizer lets common words in the natural-language query (\"the\", \"course\", \"about\") dominate, so it retrieves zero Pinecone-relevant chunks and fails outright. Semantic search (OpenAI embeddings) retrieves all 5 of the most relevant chunks and produces the most complete answer; rewritten_reranked's rewritten query pulls in the same ANN-index/metadata-filter/autoscaling detail plus the guest-lecture and direct Pinecone-storage chunks, producing an equally comprehensive answer. Hybrid recovers a decent but thinner answer via its semantic leg.",
    },
    "What does Aishwarya Srinivasan say about embeddings?": {
        "semantic": "Retrieval: Good (4/5 relevant - \"Understanding Embeddings\", \"The Building Blocks of LLMs: Transformers, Tokens, and Context\", \"Choosing an Embedding Model\", and \"AI Builder of the Week\"). Generation: Excellent - detailed, correctly attributed, covers the numerical-representation analogy, vector ranges (-1 to +1), and model-selection criteria (parameter size, context length, domain).",
        "bm25": "Retrieval: Failed (0/5 relevant - \"AI Builder of the Week\" (name-mention), Week 1 PDF cover slides, \"Live Demo: create_agent\", and \"Meet Your Instructors\" - all name/title mentions, zero embeddings content). Generation: Honest failure - \"context does not contain any information about Aishwarya Srinivasan's views... cannot answer\".",
        "hybrid": "Retrieval: Partial (2/5 relevant - \"Understanding Embeddings\" and \"The Building Blocks of LLMs\" recovered via the semantic leg). Generation: Excellent - nearly matches semantic, covering the numerical-representation/comparison analogy and vector ranges, though it misses the model-selection criteria semantic includes.",
        "rewritten_reranked": "Retrieval: Good (4/5 relevant - \"Understanding Embeddings\", \"The Vector Search Pipeline\", and \"Choosing an Embedding Model\" (all explicitly Aishwarya Srinivasan chapters), plus a \"Recap of the Previous Session's Key Concepts\" chunk; 1 slot on LLM token/context windows is tangential). Generation: Excellent - covers the numerical-representation/comparison analogy, vector ranges (-1 to +1), multi-modal embeddings (text/audio/video), AND the model-selection criteria (parameter size, context length, domain) - matches semantic's full coverage, including the detail hybrid was missing.",
        "winner": "Semantic / Rewritten+Reranked (tie)",
        "why": "BM25 still over-indexes on the literal name \"Aishwarya Srinivasan\" (appearing on nearly every slide title and as a speaker label) without any pull toward \"embeddings\", producing 5 name-only matches and a complete non-answer - unchanged by the embedding swap, since this is a BM25 tokenization issue, not a semantic one. Semantic (OpenAI embeddings) correctly captures the speaker+topic combination and gives the most complete answer; rewritten_reranked retrieves the same three Aishwarya-Srinivasan-attributed chapters and produces an equally complete answer, including the model-selection criteria that hybrid's retrieval missed. Query rewriting doesn't help BM25 here, since the original query is dominated by a literal name regardless.",
    },
    "vector database": {
        "semantic": "Retrieval: Excellent (5/5 relevant - Week 2-Session 1.pdf p.12/p.13 (definitions + ANN search), \"Demo Part 1\" (Pinecone usage), and two \"Introduction to Vector Databases\" chunks). Generation: Excellent - comprehensive, covering storage/ANN search, the dataset/embeddings/metadata breakdown, and Pinecone's specific features (ANN index, metadata filters, autoscaling).",
        "bm25": "Retrieval: Good (2/5 strongly relevant - p.12 and \"Introduction to Vector Databases\"; the other 3 are tangential quiz/text-splitter/retrieval-strategy chunks). Generation: Excellent - covers storage, ANN methods (HNSW/IVF/PQ) by name, the dataset/embeddings/metadata breakdown, and semantic-vs-SQL framing - comparable depth to semantic.",
        "hybrid": "Retrieval: Good (3/5 relevant - p.12, \"Introduction to Vector Databases\", and \"Demo Part 1\"; 2 BM25-only quiz/text-splitter chunks add little). Generation: Excellent - covers storage, ANN search, dataset/embeddings/metadata, and semantic-vs-SQL framing, very close to BM25's answer.",
        "rewritten_reranked": "Retrieval: Excellent (5/5 relevant - the \"dataset/embeddings/metadata\" breakdown, the \"why a vector database (and not just a list)\" slide, \"Introduction to Vector Databases\", the SQL-vs-vector-DB framing, and the \"how vector search actually runs\"/ANN slide). Generation: Excellent - covers the definition, the dataset/embeddings/metadata breakdown, ANN-based logarithmic-time search, a concrete BigQuery/Salesforce example, and Pinecone's specific features - on par with the other three methods.",
        "winner": "Semantic (near four-way tie)",
        "why": "\"Vector database\" remains a core, heavily-covered topic - all four methods produce comprehensive, accurate answers. Semantic edges ahead slightly by being the only one to surface Pinecone's specific managed-DB features (ANN index, metadata filters, autoscaling) alongside the general vector-DB definition; BM25, hybrid, and rewritten_reranked all give excellent but slightly more generic answers. The near-identical quality across all four confirms this remains an \"easy\" control case regardless of retrieval method.",
    },
    "How can you tell if a chatbot's answer is good or bad?": {
        "semantic": "Retrieval: Excellent (4/5 relevant - three \"RAG Evaluation Metrics\" chunks plus \"Live Q&A Session\" on evaluating RAG; one \"From Traditional to Agentic Automation\" chunk is more tangential). Generation: Best - uniquely combines both perspectives: online user-feedback signals (follow-up questions = dissatisfaction) AND offline metrics (relevancy, accuracy, faithfulness).",
        "bm25": "Retrieval: Partial (2/5 relevant - two \"Measuring and Optimizing Context\" chunks and \"Introduction to RAG Evaluation\"; \"Use Cases for RAG\" and \"Context Engineering with Many Tools\" are tangential). Generation: Good - well-structured, lists concrete criteria (relevance, clarity, completeness, conciseness, perspective) plus the golden-dataset concept, but only covers the offline-metrics perspective.",
        "hybrid": "Retrieval: Good (4/5 relevant - two \"Measuring and Optimizing Context\" and two \"RAG Evaluation Metrics\" chunks). Generation: Good - covers the online user-feedback signal (follow-up questions) plus qualitative metrics (length, clarity, multiple perspectives), but doesn't use the relevancy/accuracy/faithfulness framing semantic does.",
        "rewritten_reranked": "Retrieval: Good (3/5 relevant - an online-feedback-signal chunk (\"once you roll out your knowledge base search... you don't know what employees...\"), a \"faithfulness is one of the most important\" metrics chunk, and the \"§12 RAG EVALS: RAGAS/TruLens\" frameworks chunk; 2 slots on rerankers and small-language-model anomalies are tangential). Generation: Best (tied with semantic) - combines the online user-feedback signal (follow-up questions indicate dissatisfaction), the offline \"LLM as a judge\" approach, faithfulness/precision/recall metrics, the \"Building a Golden Dataset for Evaluation\" reference, AND names RAGAS/TruLens by name - the most complete answer of the four.",
        "winner": "Semantic / Rewritten+Reranked (tie)",
        "why": "With OpenAI embeddings, semantic retrieval alone now surfaces enough chunks to combine both the online (user-feedback/follow-up-questions) and offline (relevancy/accuracy/faithfulness metrics) evaluation perspectives in a single answer - previously this required hybrid's merge of semantic + BM25 results. rewritten_reranked also combines both perspectives and additionally names the RAGAS/TruLens frameworks by name via its §12 RAG EVALS chunk, making it at least as complete as semantic. Hybrid still produces a good answer combining online feedback with qualitative metrics, but doesn't reach the relevancy/accuracy/faithfulness framing; BM25 covers only the offline-criteria perspective.",
    },
}


def build_csv():
    rag_eval = json.loads(RAG_EVAL_PATH.read_text())
    answers = {(r["question"], r["method"]): r["answer"] for r in rag_eval}

    rows = []
    for question, analysis in ANALYSIS.items():
        row = {"Question": question, "Winner": analysis["winner"], "Why": analysis["why"]}
        for method, column in (("semantic", "Semantic"), ("bm25", "BM25"), ("hybrid", "Hybrid"), ("rewritten_reranked", "Rewritten+Reranked")):
            answer = answers[(question, method)]
            row[column] = f"{answer}\n\nVerdict: {analysis[method]}"
        rows.append(row)

    with open(OUTPUT_PATH, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["Question", "Semantic", "BM25", "Hybrid", "Rewritten+Reranked", "Winner", "Why"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote {len(rows)} rows to {OUTPUT_PATH}")


if __name__ == "__main__":
    build_csv()
