"""Coaching action layer for `compass coach`.

Compass is a learning coach, not a one-time repo profiler. The product loop
is: observe artifacts -> update learner model -> infer demonstrated
capabilities -> identify learning gaps -> recommend next concept/project ->
reassess after the learner builds more. `profile`/`explain`/`story` cover
observation and inference; this module is the recommendation step.

Selection is evidence-bounded LLM coaching, not deterministic single-target
selection: the planner produces a fixed candidate packet (eligible /
near-eligible / blocked-with-reasons skills, demonstrated strengths,
archetype context), and the LLM is asked to choose ONE next skill (plus an
optional alternative) from exactly that packet, with a rationale. The "what
to build" and "confirming evidence" fields are never generated by the LLM —
they are always a deterministic lookup from build_suggestions.yaml /
evidence_signals.yaml for whichever skill ends up chosen, so those two
fields are grounded by construction rather than by validating free text.

This module does not run a second gap-analysis engine. plan_next_milestone
and the prerequisite/activation-gate predicates in planner.py remain the
single source of truth for what is eligible/near-eligible/blocked —
prerequisite graph, activation gates, velocity, and depth thresholds are
untouched (imported, not reimplemented). If the LLM is unavailable, returns
malformed output, or chooses a skill outside the candidate packet, the
recommendation falls back to the deterministic top-priority pick.
"""
from __future__ import annotations

import json

from dataclasses import dataclass, field

import openai

from .. import _data
from ..config import OPENAI_API_KEY, OPENAI_MODEL
from ..models import LearnerState
from .narrative import ProfileNarrative, build_profile_narrative, confidence_label, zone
from .planner import _activation_gate_met, _prereqs_met, compute_velocity, plan_next_milestone

_CLOSE_TO_NEXT_CAP = 4

# How close an unmet prerequisite/gate must be (in effective_score terms) to
# count as "near-eligible" rather than "blocked" — same units as the
# planner's own min_prerequisite_score / activation_gate min_score.
_NEAR_MARGIN = 0.15
_MAX_ELIGIBLE_IN_PROMPT = 12
_MAX_NEAR_IN_PROMPT = 8
_MAX_BLOCKED_IN_PROMPT = 5

# Mirrors planner.py's _prereqs_met threshold adjustment — duplicated here
# (not imported) because this module needs the *distance* to a threshold,
# not just the met/not-met boolean planner.py exposes.
_THRESHOLD_ADJ = {"high": -0.05, "moderate": 0.0, "low": 0.05, "stalled": 0.10}


@dataclass
class CoachingRecommendation:
    mode: str  # "no_evidence" | "normal" | "re_engagement" | "no_eligible_skills"
    demonstrated: list[str] = field(default_factory=list)
    archetype: str = ""
    close_to_next: list[str] = field(default_factory=list)
    target_skill_id: str | None = None
    target_skill_name: str | None = None
    target_domain_name: str | None = None
    rationale: str = ""
    build_suggestion: str | None = None
    confirming_evidence: list[str] = field(default_factory=list)
    source: str = "deterministic"  # "llm" | "deterministic"
    fallback_reason: str | None = None
    alternative_skill_name: str | None = None
    alternative_rationale: str | None = None


@dataclass
class SkillCandidate:
    skill_id: str
    name: str
    domain_name: str
    priority: float | None
    build_suggestion: str
    confirming_evidence: list[str]


@dataclass
class BlockedSkill:
    skill_id: str
    name: str
    domain_name: str
    block_reason: str


@dataclass
class CandidatePacket:
    evidence_summary: list[str]
    archetype: str
    secondary_clusters: list[str]
    emerging_clusters: list[str]
    eligible: list[SkillCandidate] = field(default_factory=list)
    near_eligible: list[SkillCandidate] = field(default_factory=list)
    blocked_relevant: list[BlockedSkill] = field(default_factory=list)


@dataclass
class LLMCoachChoice:
    chosen_skill_id: str
    alternative_skill_id: str | None
    rationale: str
    alternative_rationale: str | None


def _ai_core_skill_ids(state: LearnerState, ai_skill_ids: set[str]) -> set[str]:
    return {
        sid for sid, score in state.skill_graph.items()
        if sid in ai_skill_ids and zone(score.current_score, score.experience_score) == "core"
    }


def _demonstrated_core_skill_ids_ranked(state: LearnerState, ai_skill_ids: set[str]) -> list[str]:
    """All core AI skills, ranked by score — the uncapped set. Used as the single
    source of truth for both the LLM's evidence_summary and the CLI's "What you've
    demonstrated" panel, so the rationale can never reference a skill the user
    wasn't also shown (narrative.strengths is deliberately capped at 5 for the
    `profile` command's curated view; coach mode needs the full list instead)."""
    core_ids = _ai_core_skill_ids(state, ai_skill_ids)
    return sorted(core_ids, key=lambda sid: state.skill_graph[sid].current_score, reverse=True)


def _archetype_name_for_skill(skill_id: str) -> str | None:
    arch_id = _data.skill_archetype_map().get(skill_id)
    if not arch_id:
        return None
    return next((a["name"] for a in _data.archetypes()["archetypes"] if a["id"] == arch_id), arch_id)


def _archetype_clause(target_archetype_name: str | None, narrative: ProfileNarrative) -> str:
    if not target_archetype_name:
        return ""
    primary_names = [n.strip() for n in narrative.archetype.split(" & ")]
    if target_archetype_name in primary_names:
        return f"strengthens your {target_archetype_name} identity"
    if target_archetype_name in narrative.secondary_clusters or target_archetype_name in narrative.emerging_clusters:
        return f"builds your emerging {target_archetype_name} cluster"
    return f"would establish your first foothold in {target_archetype_name}"


def _evidence_repo_hint(state: LearnerState, prereq_ids: list[str]) -> str:
    """If every demonstrated prereq's strongest evidence traces to one repo, name it."""
    repos: set[str] = set()
    for ev in state.evidence:
        if ev.skill_id in prereq_ids and ev.evidence_type == "observed" and ev.source == "scan" and ev.source_repo:
            repos.add(ev.source_repo)
    if len(repos) == 1:
        return f" in {next(iter(repos))}"
    return ""


def _build_rationale(
    state: LearnerState,
    skill_meta: dict,
    target_id: str,
    core_ids: set[str],
    target_domain_name: str,
    narrative: ProfileNarrative,
) -> str:
    """Deterministic fallback rationale — used only when the LLM is unavailable
    or its choice fails hard validation."""
    name = skill_meta[target_id]["name"]
    prereqs = skill_meta[target_id].get("prerequisites", [])
    demonstrated_prereqs = [p for p in prereqs if p in core_ids]

    if demonstrated_prereqs:
        prereq_names = [skill_meta[p]["name"] for p in demonstrated_prereqs]
        if len(prereq_names) == 1:
            prereq_text = prereq_names[0]
        else:
            prereq_text = ", ".join(prereq_names[:-1]) + f", and {prereq_names[-1]}"
        hint = _evidence_repo_hint(state, demonstrated_prereqs)
        base = f"{name} builds on {prereq_text}, which you've already demonstrated{hint}."
    else:
        base = f"{name} has no unmet prerequisites yet — it's a natural starting point."

    archetype_clause = _archetype_clause(_archetype_name_for_skill(target_id), narrative)
    if archetype_clause:
        base += f" This is the next step in {target_domain_name}, which {archetype_clause}."
    else:
        base += f" This is the next step in {target_domain_name}."
    return base


def _confirming_evidence(target_id: str) -> list[str]:
    gh = _data.evidence_signals().get("skills", {}).get(target_id, {}).get("github", {})
    seen: list[str] = []
    for level in ("strong", "moderate"):
        for entry in gh.get(level, []):
            desc = entry.get("description", "") if isinstance(entry, dict) else ""
            if desc and desc not in seen:
                seen.append(desc)
    return seen


def _resume_target(state: LearnerState, ai_skill_ids: set[str]) -> str | None:
    """Most recently touched AI skill still in 'learning' zone — the in-progress thread to resume."""
    candidates = [
        (sid, score.last_updated)
        for sid, score in state.skill_graph.items()
        if sid in ai_skill_ids and zone(score.current_score, score.experience_score) == "learning"
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda x: x[1])[0]


def _entry_point_in_unevidenced_domain(state: LearnerState, skill_meta: dict) -> str | None:
    """An entry-point skill (no prerequisites) from an AI domain with zero evidence so far."""
    domains_with_evidence = {
        meta["domain"] for sid, meta in skill_meta.items()
        if (s := state.skill_graph.get(sid)) and s.current_score > 0
    }
    for skill_id, meta in skill_meta.items():
        if not meta.get("prerequisites") and meta["domain"] not in domains_with_evidence:
            return skill_id
    return None


# ── Candidate packet (the deterministic planner's bounded search space) ──────

def _prereq_distance(meta: dict, skill_graph: dict, velocity_tier: str) -> float:
    base_thresh = meta.get("min_prerequisite_score", 0.30)
    thresh = max(0.0, base_thresh + _THRESHOLD_ADJ.get(velocity_tier, 0.0))
    max_gap = 0.0
    for prereq_id in meta.get("prerequisites", []):
        s = skill_graph.get(prereq_id)
        eff = s.effective_score if s else 0.0
        if eff < thresh:
            max_gap = max(max_gap, thresh - eff)
    return max_gap


def _gate_distance(meta: dict, skill_graph: dict) -> float:
    gate = meta.get("activation_gate")
    if not gate:
        return 0.0
    any_of = gate.get("any_of", [])
    min_s = gate.get("min_score", 0.30)
    best = max((skill_graph[sid].effective_score for sid in any_of if skill_graph.get(sid) is not None), default=0.0)
    return max(0.0, min_s - best)


def _block_reason(skill_meta: dict, meta: dict, skill_graph: dict, velocity_tier: str) -> str:
    parts: list[str] = []
    base_thresh = meta.get("min_prerequisite_score", 0.30)
    thresh = max(0.0, base_thresh + _THRESHOLD_ADJ.get(velocity_tier, 0.0))
    for prereq_id in meta.get("prerequisites", []):
        s = skill_graph.get(prereq_id)
        eff = s.effective_score if s else 0.0
        if eff < thresh:
            parts.append(f"{skill_meta[prereq_id]['name']} ≥{thresh:.2f} (currently {eff:.2f})")
    gate = meta.get("activation_gate")
    if gate:
        any_of = gate.get("any_of", [])
        min_s = gate.get("min_score", 0.30)
        best = max((skill_graph[sid].effective_score for sid in any_of if skill_graph.get(sid) is not None), default=0.0)
        if best < min_s:
            names = " or ".join(skill_meta[sid]["name"] for sid in any_of)
            parts.append(f"one of [{names}] ≥{min_s:.2f} (currently best {best:.2f})")
    return "; ".join(parts) if parts else "blocked"


def build_candidate_packet(state: LearnerState) -> CandidatePacket:
    """The deterministic, bounded search space the LLM coach is allowed to choose from.

    Reuses plan_next_milestone's own eligibility predicates (_prereqs_met,
    _activation_gate_met) rather than reimplementing gap analysis — this
    function only adds two new bins (near-eligible, blocked-but-relevant)
    on top of the same rules, for richer context than a single domain pick.
    """
    narrative = build_profile_narrative(state)
    skill_meta = _data.skill_metadata()
    depth_thresh = _data.depth_threshold(state.profile.desired_depth)
    velocity = compute_velocity(state)
    skip_set = {o.target for o in state.overrides if o.type == "not_interested"}
    plan = plan_next_milestone(state)
    ai_skill_ids = set(_data.all_skill_ids())

    priority_lookup: dict[str, float] = {}
    if plan.top:
        priority_lookup.update(plan.top.skill_priorities)
    for c in plan.horizon:
        priority_lookup.update(c.skill_priorities)

    eligible_ids: set[str] = set()
    near: list[tuple[str, float]] = []
    blocked: list[str] = []

    for skill_id, meta in skill_meta.items():
        s = state.skill_graph.get(skill_id)
        effective = s.effective_score if s else 0.0
        if effective >= depth_thresh:
            continue
        if skill_id in skip_set or meta["domain"] in skip_set:
            continue
        if _prereqs_met(meta, state.skill_graph, velocity.tier) and _activation_gate_met(meta, state.skill_graph):
            eligible_ids.add(skill_id)
            continue
        distance = max(_prereq_distance(meta, state.skill_graph, velocity.tier), _gate_distance(meta, state.skill_graph))
        if distance <= _NEAR_MARGIN:
            near.append((skill_id, distance))
        else:
            blocked.append(skill_id)

    domain_name_map = {d["id"]: d["name"] for d in _data.domains()}

    def _to_candidate(skill_id: str) -> SkillCandidate:
        return SkillCandidate(
            skill_id=skill_id,
            name=skill_meta[skill_id]["name"],
            domain_name=domain_name_map.get(skill_meta[skill_id]["domain"], skill_meta[skill_id]["domain"]),
            priority=priority_lookup.get(skill_id),
            build_suggestion=_data.build_suggestion(skill_id) or "",
            confirming_evidence=_confirming_evidence(skill_id),
        )

    eligible_sorted = sorted(eligible_ids, key=lambda sid: priority_lookup.get(sid, 0.0), reverse=True)
    near_sorted = [sid for sid, _ in sorted(near, key=lambda x: x[1])]

    # "Relevant" blocked skills: one hop away from something already in
    # reach (demonstrated, eligible, or near-eligible) — bounds the list to
    # what's actually pedagogically informative instead of every locked skill.
    reachable = eligible_ids | set(near_sorted) | _ai_core_skill_ids(state, ai_skill_ids)
    blocked_relevant = [
        sid for sid in blocked
        if any(p in reachable for p in skill_meta[sid].get("prerequisites", []))
        or (
            skill_meta[sid].get("activation_gate")
            and any(g in reachable for g in skill_meta[sid]["activation_gate"].get("any_of", []))
        )
    ]

    demonstrated_ranked = _demonstrated_core_skill_ids_ranked(state, ai_skill_ids)
    evidence_summary = [
        f"{skill_meta[sid]['name']} — {confidence_label(state.skill_graph[sid].current_score)} confidence"
        for sid in demonstrated_ranked
    ]

    return CandidatePacket(
        evidence_summary=evidence_summary,
        archetype=narrative.archetype,
        secondary_clusters=narrative.secondary_clusters,
        emerging_clusters=narrative.emerging_clusters,
        eligible=[_to_candidate(sid) for sid in eligible_sorted[:_MAX_ELIGIBLE_IN_PROMPT]],
        near_eligible=[_to_candidate(sid) for sid in near_sorted[:_MAX_NEAR_IN_PROMPT]],
        blocked_relevant=[
            BlockedSkill(
                skill_id=sid,
                name=skill_meta[sid]["name"],
                domain_name=domain_name_map.get(skill_meta[sid]["domain"], skill_meta[sid]["domain"]),
                block_reason=_block_reason(skill_meta, skill_meta[sid], state.skill_graph, velocity.tier),
            )
            for sid in blocked_relevant[:_MAX_BLOCKED_IN_PROMPT]
        ],
    )


# ── LLM coaching judgment, bounded to the candidate packet ──────────────────

_COACH_SYSTEM_PROMPT = """You are an AI learning coach. A deterministic planner has already \
computed the full set of skills this learner could plausibly work on next, split into \
ELIGIBLE (unlocked now), NEAR-ELIGIBLE (unlocked very soon), and BLOCKED (context only). \
Your job is coaching judgment, not gap analysis: pick whichever ELIGIBLE or NEAR-ELIGIBLE \
skill is the most pedagogically sound next step for this specific learner, given their \
demonstrated strengths and archetype — not necessarily whichever has the highest raw \
planner_priority number.

Hard rules:
- chosen_skill_id and alternative_skill_id (if given) MUST be copied exactly from an "id=" \
  field under ELIGIBLE or NEAR-ELIGIBLE. Never choose a BLOCKED skill. Never invent a skill_id.
- Do not invent evidence, scores, or facts not present below.
- rationale must reference only the demonstrated strengths, archetype, and skill names given.

Respond with strict JSON only, no markdown fences, matching exactly:
{"chosen_skill_id": "...", "alternative_skill_id": "..." or null, "rationale": "...", "alternative_rationale": "..." or null}
"""


def _format_packet_for_prompt(packet: CandidatePacket) -> str:
    lines: list[str] = []
    lines.append("DEMONSTRATED STRENGTHS:")
    lines.extend(f"  - {s}" for s in (packet.evidence_summary or ["(none yet)"]))
    lines.append(f"\nARCHETYPE: {packet.archetype}")
    if packet.secondary_clusters:
        lines.append("SECONDARY CLUSTERS: " + ", ".join(packet.secondary_clusters))
    if packet.emerging_clusters:
        lines.append("EMERGING CLUSTERS: " + ", ".join(packet.emerging_clusters))

    lines.append("\nELIGIBLE (selectable now):")
    for c in packet.eligible:
        lines.append(f'  - id="{c.skill_id}" name="{c.name}" domain="{c.domain_name}" planner_priority={c.priority}')

    lines.append("\nNEAR-ELIGIBLE (selectable, one small gap from fully unlocked):")
    for c in packet.near_eligible:
        lines.append(f'  - id="{c.skill_id}" name="{c.name}" domain="{c.domain_name}"')

    if packet.blocked_relevant:
        lines.append("\nBLOCKED (context only — do NOT select these):")
        for b in packet.blocked_relevant:
            lines.append(f'  - id="{b.skill_id}" name="{b.name}" reason: {b.block_reason}')

    return "\n".join(lines)


def _request_llm_choice(prompt: str) -> str | None:
    """Returns the raw LLM response text, or None if the LLM is unavailable/erroring.
    Factored out from parsing/validation so tests can monkeypatch this single seam."""
    if not OPENAI_API_KEY:
        return None
    try:
        client = openai.OpenAI(api_key=OPENAI_API_KEY)
        response = client.chat.completions.create(
            model=OPENAI_MODEL,
            max_tokens=500,
            messages=[
                {"role": "system", "content": _COACH_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
        )
        return response.choices[0].message.content.strip()
    except openai.OpenAIError:
        return None


def _parse_llm_choice(raw: str | None) -> LLMCoachChoice | None:
    if not raw:
        return None
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
    try:
        data = json.loads(text)
        chosen = data.get("chosen_skill_id")
        if not chosen or not isinstance(chosen, str):
            return None
        rationale = str(data.get("rationale") or "").strip()
        if not rationale:
            return None
        alt_rationale = data.get("alternative_rationale")
        return LLMCoachChoice(
            chosen_skill_id=chosen,
            alternative_skill_id=data.get("alternative_skill_id") or None,
            rationale=rationale,
            alternative_rationale=str(alt_rationale).strip() if alt_rationale else None,
        )
    except (json.JSONDecodeError, AttributeError, TypeError, IndexError):
        return None


def _validate_choice(choice: LLMCoachChoice, packet: CandidatePacket) -> bool:
    """All-or-nothing: any reference to a skill outside the candidate packet
    invalidates the entire response, not just that one field."""
    allowed = {c.skill_id for c in packet.eligible} | {c.skill_id for c in packet.near_eligible}
    if choice.chosen_skill_id not in allowed:
        return False
    if choice.alternative_skill_id is not None:
        if choice.alternative_skill_id not in allowed or choice.alternative_skill_id == choice.chosen_skill_id:
            return False
    return True


def _llm_coach_choice(packet: CandidatePacket) -> tuple[LLMCoachChoice | None, str | None]:
    """Returns (choice, fallback_reason). choice is None iff fallback_reason is set."""
    if not packet.eligible and not packet.near_eligible:
        return None, "no eligible or near-eligible candidates"
    raw = _request_llm_choice(_format_packet_for_prompt(packet))
    if raw is None:
        return None, "LLM unavailable (no API key or request error)"
    parsed = _parse_llm_choice(raw)
    if parsed is None:
        return None, "LLM response could not be parsed as valid JSON"
    if not _validate_choice(parsed, packet):
        return None, "LLM chose a skill outside the eligible/near-eligible candidate set"
    return parsed, None


def build_coaching_recommendation(state: LearnerState) -> CoachingRecommendation:
    if not state.evidence:
        return CoachingRecommendation(
            mode="no_evidence",
            rationale="No evidence yet — run `compass scan --repo <path>` or `compass run <path>` first.",
        )

    narrative = build_profile_narrative(state)
    skill_meta = _data.skill_metadata()
    ai_skill_ids = set(_data.all_skill_ids())
    core_ids = _ai_core_skill_ids(state, ai_skill_ids)
    plan = plan_next_milestone(state)
    domain_name_map = {d["id"]: d["name"] for d in _data.domains()}

    if plan.re_engagement_mode:
        target_id = _resume_target(state, ai_skill_ids)
        close_ids = [
            sid for sid, score in state.skill_graph.items()
            if sid in ai_skill_ids and sid != target_id and zone(score.current_score, score.experience_score) == "learning"
        ][:_CLOSE_TO_NEXT_CAP]
        if target_id is None:
            return CoachingRecommendation(
                mode="re_engagement",
                demonstrated=narrative.strengths,
                archetype=narrative.archetype,
                rationale="You've been away and nothing is currently in progress — re-run `compass run` on a recent repo to pick back up.",
            )
        domain_name = domain_name_map.get(skill_meta[target_id]["domain"], skill_meta[target_id]["domain"])
        return CoachingRecommendation(
            mode="re_engagement",
            demonstrated=narrative.strengths,
            archetype=narrative.archetype,
            close_to_next=[skill_meta[sid]["name"] for sid in close_ids],
            target_skill_id=target_id,
            target_skill_name=skill_meta[target_id]["name"],
            target_domain_name=domain_name,
            rationale="Resume momentum: " + _build_rationale(state, skill_meta, target_id, core_ids, domain_name, narrative),
            build_suggestion=_data.build_suggestion(target_id),
            confirming_evidence=_confirming_evidence(target_id),
        )

    if plan.no_eligible_skills or plan.top is None:
        target_id = _entry_point_in_unevidenced_domain(state, skill_meta)
        if target_id is None:
            return CoachingRecommendation(
                mode="no_eligible_skills",
                demonstrated=narrative.strengths,
                archetype=narrative.archetype,
                rationale="All role-relevant skills are already at your target depth, and there's no unexplored AI domain left to recommend an entry point from — nice work.",
            )
        domain_name = domain_name_map.get(skill_meta[target_id]["domain"], skill_meta[target_id]["domain"])
        return CoachingRecommendation(
            mode="no_eligible_skills",
            demonstrated=narrative.strengths,
            archetype=narrative.archetype,
            target_skill_id=target_id,
            target_skill_name=skill_meta[target_id]["name"],
            target_domain_name=domain_name,
            rationale="Your role-relevant skills are already at target depth. " + _build_rationale(state, skill_meta, target_id, core_ids, domain_name, narrative),
            build_suggestion=_data.build_suggestion(target_id),
            confirming_evidence=_confirming_evidence(target_id),
        )

    # Normal mode: planner has a top milestone candidate. Build the bounded
    # candidate packet and ask the LLM for coaching judgment within it;
    # fall back to the planner's own top pick on any validation failure.
    top = plan.top
    deterministic_target = top.target_skills[0] if top.target_skills else max(top.skill_priorities, key=top.skill_priorities.get)

    packet = build_candidate_packet(state)
    choice, fallback_reason = _llm_coach_choice(packet)

    target_id = choice.chosen_skill_id if choice else deterministic_target
    target_domain_name = domain_name_map.get(skill_meta[target_id]["domain"], skill_meta[target_id]["domain"])

    if choice:
        rationale = choice.rationale
        source = "llm"
    else:
        rationale = _build_rationale(state, skill_meta, target_id, core_ids, target_domain_name, narrative)
        source = "deterministic"

    alt_name = skill_meta[choice.alternative_skill_id]["name"] if choice and choice.alternative_skill_id else None
    alt_rationale = choice.alternative_rationale if choice else None

    close_ids = [sid for sid in top.skill_priorities if sid != target_id]
    close_ids.sort(key=lambda sid: top.skill_priorities[sid], reverse=True)

    # Uncapped — must match exactly what build_candidate_packet sent the LLM
    # as evidence_summary, so a rationale can never cite a skill the user
    # wasn't also shown (narrative.strengths is capped at 5 for `profile`'s
    # curated view, which would silently truncate what coach mode displays).
    demonstrated_names = [skill_meta[sid]["name"] for sid in _demonstrated_core_skill_ids_ranked(state, ai_skill_ids)]

    return CoachingRecommendation(
        mode="normal",
        demonstrated=demonstrated_names,
        archetype=narrative.archetype,
        close_to_next=[skill_meta[sid]["name"] for sid in close_ids[:_CLOSE_TO_NEXT_CAP]],
        target_skill_id=target_id,
        target_skill_name=skill_meta[target_id]["name"],
        target_domain_name=target_domain_name,
        rationale=rationale,
        build_suggestion=_data.build_suggestion(target_id),
        confirming_evidence=_confirming_evidence(target_id),
        source=source,
        fallback_reason=fallback_reason,
        alternative_skill_name=alt_name,
        alternative_rationale=alt_rationale,
    )
